close all;
clear all;
load('rect.mat');
figure,imshow(X,Map),title('data');
E = entropyfilt(X);
Eim = mat2gray(E);
BW1 = im2bw(Eim);
BWao = bwareaopen(BW1,2000);
nhood = true(9);
closeBWao = imclose(BWao,nhood);
roughMask = imfill(closeBWao,'holes');
figure,imshow(roughMask),title('1');
I2 = X;
I2(roughMask) = 0;
figure,imshow(I2),title('2');
E2 = entropyfilt(I2);
E2im = mat2gray(E2);
figure,imshow(E2im),title('3');
BW2 = im2bw(E2im);
mask2 = bwareaopen(BW2,1000);
figure,imshow(mask2),title('4');
mask2 = bwareaopen(BW2,5000);
figure,imshow(mask2),title('5');
nhood = true(50);
closeBWao = imclose(mask2,nhood);
figure,imshow(closeBWao),title('6');
roughMask = imfill(closeBWao,'holes');
figure,imshow(roughMask),title('7');
im = double(roughMask);
lo=canny(im,1,[0.4 0.7]);
figure,imshow(lo),title('garis');
Iss=X;
rgb = imoverlay(Iss, lo, [1 0 0.5]);
figure,imshow(rgb),title('Hasil');
% texture1 = X;
% texture1(~mask2) = 0;
% texture2 = X;
% texture2(mask2) = 0;
% boundary = bwperim(mask2);
% segmentResults = X;
% segmentResults(boundary) = 255;
% figure,imshow(segmentResults),title('5');